<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-desktop</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>UnoDevelop.RegExpTk</AssemblyName>
    <RootNamespace>UnoDevelop.AddIns.Misc.RegExpTk</RootNamespace>
    <UnoSingleProject>true</UnoSingleProject>
    <UnoFeatures>SkiaRenderer</UnoFeatures>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Main\Core\Project\ICSharpCode.Core.Uno.csproj" />
    <ProjectReference Include="..\..\..\..\Main\Base\Project\ICSharpCode.SharpDevelop.Uno.csproj" />
  </ItemGroup>
</Project>
