<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-desktop</TargetFramework>
    <RootNamespace>ICSharpCode.IconEditor</RootNamespace>
    <AssemblyName>UnoDevelop.IconEditor</AssemblyName>
    <UnoSingleProject>true</UnoSingleProject>
    <UnoFeatures>SkiaRenderer</UnoFeatures>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <NoWarn>$(NoWarn);CA1416;CS0067</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Libraries\ResourceFiles\LeXtudio.OpenDevelop.ResourceFiles.csproj" />
    <ProjectReference Include="..\..\..\..\Main\Core\Project\ICSharpCode.Core.csproj" />
    <ProjectReference Include="..\..\..\..\Main\Base\Project\ICSharpCode.SharpDevelop.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="IconEditor.addin" CopyToOutputDirectory="Always" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Src\IconDisplayBinding.cs" />
    <Compile Include="Src\IconCursorViewerViewContent.cs" />
  </ItemGroup>
</Project>
