<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-desktop</TargetFramework>
    <AssemblyName>UnoDevelop.UnitTesting</AssemblyName>
    <RootNamespace>UnoDevelop.UnitTesting</RootNamespace>
    <NoWarn>$(NoWarn);CS8632</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="UnoDevelop.Core.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Base\Project\ICSharpCode.SharpDevelop.Uno.csproj" />
  </ItemGroup>
</Project>
