namespace ICSharpCode.SharpDevelop.Migration;

public static class BaseMigrationBatch
{
    public static readonly string[] LinkedFiles =
    {
        "Gui/PadDescriptor.uno.cs",
        "Workbench/IViewContent.uno.cs",
        "Workbench/IWorkbenchWindow.uno.cs",
        "Workbench/IWorkbench.uno.cs",
        "Workbench/ViewContentEventArgs.uno.cs",
        "Project/IProject.uno.cs",
        "Project/ProjectItem.uno.cs",
        "Project/ProjectBindingDescriptor.uno.cs",
        "Project/TargetFramework.uno.cs",
        "Project/ProjectLoadException.uno.cs",
        "Project/UpstreamNamespaceStubs.uno.cs",
        "Workbench/IShutdownService.cs",
        "Workbench/IPadContent.cs",
        "Workbench/ICustomizedCommands.cs",
        "Workbench/ViewContentServiceAttribute.cs",
        "Util/ICanBeDirty.cs",
        "Services/NavigationService/INavigationPoint.cs",
        "Parser/ParserBackend.cs",
        "Project/Build/BuildTarget.cs",
        "Project/Build/BuildOutputVerbosity.cs",
        "Dom/IModelCollection.cs",
        "Dom/ModelCollectionChangedEvent.cs",
        "Util/PropertyChangedEventArgs.cs",
        "Util/IProgressMonitor.cs",
        "Project/IProjectService.cs",
        "Services/ProjectService/ProjectEventHandler.cs",
        "Services/ProjectService/ProjectItemEventHandler.cs",
        "Project/Configuration/ConfigurationAndPlatform.cs",
        "Project/Configuration/ConfigurationMapping.cs",
        "Project/Configuration/IConfigurationOrPlatformNameCollection.cs",
        "Project/Configuration/IConfigurable.cs",
        "Project/IProjectBinding.cs",
        "Project/ProjectInformation.cs",
        "Project/MSBuildEnums.cs",
        "Project/MSBuildInternals.cs",
        "Project/ISolution.cs",
        "Project/ISolutionFolder.cs",
        "Project/ISolutionItem.cs",
        "Project/SolutionEventArgs.cs",
        "Project/SolutionSection.cs",
    };
}
