<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-desktop</TargetFramework>
    <RootNamespace>ICSharpCode.XamlBinding</RootNamespace>
    <AssemblyName>ICSharpCode.XamlBinding</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Main\Core\Project\ICSharpCode.Core.csproj" />
    <ProjectReference Include="..\..\..\..\Main\Base\Project\ICSharpCode.SharpDevelop.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="XamlBinding.addin" CopyToOutputDirectory="Always" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Configuration\AssemblyInfo.cs" />
    <Compile Include="Src\XamlLanguageBinding.cs" />
  </ItemGroup>
</Project>
