<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <!-- <Nullable>enable</Nullable> -->
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <SharpDevelopSourceRoot>$(MSBuildThisFileDirectory)..\externals\SharpDevelop</SharpDevelopSourceRoot>
    <AXSGRoot>$(MSBuildThisFileDirectory)..\externals\OpenDevelop\externals\vscode-wpf\external\wxsg\external\XamlToCSharpGenerator</AXSGRoot>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <UseNuGetPackages>true</UseNuGetPackages>
  </PropertyGroup>
</Project>
