<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-desktop</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>UnoDevelop.ResourceEditor</AssemblyName>
    <RootNamespace>UnoDevelop.AddIns.DisplayBindings.ResourceEditor</RootNamespace>
    <UnoSingleProject>true</UnoSingleProject>
    <UnoFeatures>SkiaRenderer</UnoFeatures>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CS0067</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="ResourceEditor.addin" CopyToOutputDirectory="Always" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Libraries\ResourceFiles\LeXtudio.OpenDevelop.ResourceFiles.csproj" />
    <ProjectReference Include="..\..\..\..\Main\Core\Project\ICSharpCode.Core.csproj" />
    <ProjectReference Include="..\..\..\..\Main\Base\Project\ICSharpCode.SharpDevelop.csproj" />
  </ItemGroup>
</Project>
